wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1666013923.756004
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.9.7
      5: 0.13.4
      8:
      - 1
      - 5
