wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: huggingface
    huggingface_version: 4.12.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1665673883.864218
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.9.7
      5: 0.13.4
      6: 4.12.5
      8:
      - 5
batch_size:
  desc: null
  value: 5
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 1.0e-05
weight_decay:
  desc: null
  value: 0.01
