wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: huggingface
    huggingface_version: 4.12.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1665747259.006908
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 1
      - 16
      - 23
      - 24
      4: 3.9.7
      5: 0.13.4
      6: 4.12.5
      8:
      - 5
batch_size:
  desc: null
  value: 5
lr_scheduler:
  desc: null
  value: <torch.optim.lr_scheduler.LambdaLR object at 0x7fcb690deaf0>
num_epochs:
  desc: null
  value: 10
num_trainig_steps:
  desc: null
  value: 70
optimizer:
  desc: null
  value: "AdamW (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    eps: 1e-08\n    initial_lr: 1e-05\n    lr: 1e-05\n    weight_decay: 0.01\n\
    )"
