wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: huggingface
    huggingface_version: 4.12.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1666014904.984355
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 23
      4: 3.9.7
      5: 0.13.4
      6: 4.12.5
      8:
      - 5
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.0015198697834052006
scheduler_form:
  desc: null
  value: linear
wd:
  desc: null
  value: 0.008119668706201929
